In [1]:
import pandas as pd

In [10]:
import os

mapping_file = pd.ExcelFile(os.path.join( 'metadata', 'vietnames_to_fiin.xlsx'))

In [16]:
df_bs = mapping_file.parse('Standard BS')[['Universal_caption', 'universal_code']]
df_is = mapping_file.parse('Standard IS')[['Universal_caption', 'universal_code']]
df_cf = mapping_file.parse('Standard CF')[['Universal_caption', 'universal_code']]

In [17]:
df_bs = df_bs.rename(columns={'Universal_caption': 'category_name', 'universal_code': 'category_code'})
df_is = df_is.rename(columns={'Universal_caption': 'category_name', 'universal_code': 'category_code'})
df_cf = df_cf.rename(columns={'Universal_caption': 'category_name', 'universal_code': 'category_code'})

df_map_fs = pd.concat([df_bs, df_is, df_cf], ignore_index=True)

df_map_fs.to_csv(os.path.join('metadata', 'map_category_code.csv'), index=False)

In [14]:
df = pd.read_parquet('../../data/financial_statement_v3.parquet')

In [15]:
df

          data stock_code  quarter    year date_added category_code
0          0.0        SSI      0.0  2010.0 2010-12-30        IS_003
1          0.0        SSI      0.0  2011.0 2011-12-30        IS_003
2          0.0        SSI      0.0  2012.0 2012-12-30        IS_003
3          0.0        SSI      0.0  2013.0 2013-12-30        IS_003
4          0.0        SSI      0.0  2014.0 2014-12-30        IS_003
...        ...        ...      ...     ...        ...           ...
162755  1747.0        DGC      3.0  2024.0 2024-09-30        IS_140
162756  1849.0        DGC      4.0  2024.0 2024-12-30        IS_140
162757  2003.0        DGC      1.0  2025.0 2025-03-30        IS_140
162758  2085.0        DGC      2.0  2025.0 2025-06-30        IS_140
162759  1860.0        DGC      3.0  2025.0 2025-09-30        IS_140

[162760 rows x 6 columns]

In [ ]:
df = df.dropna(subset=['category_code'])

In [19]:
df.to_parquet('../../data/financial_statement_v3.parquet', index=False)

In [16]:
df_tm = pd.read_parquet('../../data/financial_statement_explaination_v3.parquet')

In [17]:
df = pd.concat([df, df_tm])

In [18]:
df

        data stock_code  quarter    year date_added category_code
0        0.0        SSI      0.0  2010.0 2010-12-30        IS_003
1        0.0        SSI      0.0  2011.0 2011-12-30        IS_003
2        0.0        SSI      0.0  2012.0 2012-12-30        IS_003
3        0.0        SSI      0.0  2013.0 2013-12-30        IS_003
4        0.0        SSI      0.0  2014.0 2014-12-30        IS_003
...      ...        ...      ...     ...        ...           ...
218043   0.0        DGC      3.0  2024.0 2024-09-30   Corp_TM_157
218044   0.0        DGC      4.0  2024.0 2024-12-30   Corp_TM_157
218045   0.0        DGC      1.0  2025.0 2025-03-30   Corp_TM_157
218046   0.0        DGC      2.0  2025.0 2025-06-30   Corp_TM_157
218047   0.0        DGC      3.0  2025.0 2025-09-30   Corp_TM_157

[380808 rows x 6 columns]

In [5]:
df[df['category_code'] == 'IS_090']

,data,stock_code,quarter,year,date_added,universal_code_x,universal_code_y,category_code
720,0.000000,SSI,0.0,2010.0,2010-12-30,None,None,IS_090
721,0.000000,SSI,0.0,2011.0,2011-12-30,None,None,IS_090
722,0.000000,SSI,0.0,2012.0,2012-12-30,None,None,IS_090
723,0.000000,SSI,0.0,2013.0,2013-12-30,None,None,IS_090
724,-183.144865,SSI,0.0,2014.0,2014-12-30,None,None,IS_090
...,...,...,...,...,...,...,...,...
157085,-61.995634,DGC,3.0,2024.0,2024-09-30,None,None,IS_090
157086,-79.776846,DGC,4.0,2024.0,2024-12-30,None,None,IS_090
157087,-141.122729,DGC,1.0,2025.0,2025-03-30,None,None,IS_090
157088,-95.468665,DGC,2.0,2025.0,2025-06-30,None,None,IS_090
157089,-96.897791,DGC,3.0,2025.0,2025-09-30,None,None,IS_090